version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=password123
      - DB_NAME=crud_demo
      - DB_PORT=5432
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge