apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-server
  labels:
    app: go-web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-web-server
  template:
    metadata:
      labels:
        app: go-web-server
    spec:
      containers:
      - name: go-web-server
        image: parthtiwari/go-web-server:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_NAME
          value: crud_demo
        - name: DB_PORT
          value: "5432"
        - name: SERVER_PORT
          value: "5000"
          
            

    